version: "3.9"
services:
  llm-backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    #volumes:
      #- ./db.sqlite3:/app/db.sqlite3

  llm-frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
